settings:
  #Computer name with no spaces
  name: "ComputerName"
  debug: False
  sensor_time: 5
  network: XXX.XXX.XXX.XXX

mqtt_server:
  server: "ip or url from mqtt broker"
  port: 1883
  userName: "username"
  password: "password"

ohm:
  path: "path"

apps:
  plex:
    name: "Plex Media Server"
    path: "C:\\Program Files (x86)\\Plex\\Plex Media Server\\"
    process: "Plex Media Server.exe"
    md-icon: "mdi:plex"
  utorrent:
    name: "uTorrent"
    path: "C:\\Program Files (x86)\\uTorrent\\"
    process: "uTorrent.exe"
  spotify:
    name: "Spotify"
    path: "%APPDATA%\\Spotify\\"
    process: "Spotify.exe"
    md-icon: "mdi:spotify"